services:
  client-react:
    container_name: "client-react"
    image: client-react
    build:
      context: ./client-react/
    init: true
    volumes:
      - type: bind
        source: ./client-react
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: bind
        source: ./client-react/vite.config.ts
        target: /usr/src/app/vite.config.ts
    networks:
      - frontend
    ports:
      - 5173:5173
  api-golang:
    container_name: "api-golang"
    env_file: ".env"
    image: api-golang
    build:
      context: ./api-golang/
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./api-golang/
        target: /app/
    networks:
      - backend
      - frontend
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: postgres:12.19-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=${POSTGRES_USER}
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  backend:
  frontend:
