services:
  api-golang:
    env_file: ".env"
    image: api-golang
    build:
      context: ./api-golang/
    init: true
  db:
    image: postgres:12.19-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=${POSTGRES_USER}
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  backend:
