services:
  api-golang:
    command:
      - "dlv"
      - "debug"
      - "/app/"
      - "--listen=:4000"
      - "--headless=true"
      - "--log=true"
      # - "--log-output=debugger,debuglineerr,gdbwire,lldbout,rpc"
      # - "--accept-multiclient"
      # - "--continue"
      - "--api-version=2"
    ports:
      - "3000:3000"
      # delve debug port
      - "4000:4000"
